### PR TITLE
feat: support Redis cluster

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

fixes: #5

### CODE REVIEW

**Comment by hsluoyz** [comment]
@family2hu please review.

**Review by family2hu — COMMENTED** [review]
looks perfect, please publish in npm and I all check in my project.

**Comment by hsluoyz** [comment]
@nodece plz fix CI.

**Comment by nodece** [comment]
Waiting to be resolved: #https://github.com/luin/ioredis/issues/1223

**Comment by hsluoyz** [comment]
@nodece do we have to use ioredis? That project doesn't seem to be very responsive..

**Comment by nodece** [comment]
@hsluoyz We can only use ioredis. Other clients do not support cluster.

**Comment by nodece** [comment]
new PR: #7

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/node-casbin/redis-watcher/pull/7

**Pull request closed without merging**
